name: example
description: A new jaspr project.
publish_to: none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  jaspr: ^0.16.2
  jaspr_router: ^0.6.0
  flex:
    path: ../  # Reference to local package

dev_dependencies:
  build_runner: ^2.4.0
  jaspr_web_compilers: ^4.0.10+1
  jaspr_builder: ^0.16.2
  jaspr_lints: ^0.1.2
  lints: ^3.0.0

jaspr:
  mode: server

